#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Convert a splash BMP to packed monochrome pixels for the RTD OSD."""
import argparse
from pathlib import Path

from PIL import Image, UnidentifiedImageError


def convert(source, output):
    with Image.open(source) as image:
        if image.format != "BMP":
            raise ValueError("Input must be a BMP file")
        width, height = image.size
        if not (1 <= width <= 192 and 1 <= height <= 108):
            raise ValueError("BMP must be between 1x1 and 192x108 pixels (displayed at 4x)")
        # Explicit threshold avoids dithering and honors indexed BMP palettes.
        pixels = image.convert("L").point(lambda value: 255 if value >= 128 else 0)
        data = pixels.convert("1", dither=Image.Dither.NONE).tobytes()

    lines = [
        "/* Generated by tools/bmp_to_header.py; edit assets/splash.bmp instead.",
        " * Pixel data retains the artwork's license; see assets/README.md.",
        " * One bit per pixel, MSB first; rows padded to whole bytes.",
        " */",
        "#ifndef RTD_SPLASH_BITMAP_H",
        "#define RTD_SPLASH_BITMAP_H",
        "",
        f"#define SPLASH_BITMAP_WIDTH {width}u",
        f"#define SPLASH_BITMAP_HEIGHT {height}u",
        "",
        "static const OSD_CODE uint8_t splash_bitmap[] = {",
    ]
    stride = (width + 7) // 8
    for start in range(0, len(data), stride):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in data[start:start + stride]) + ",")
    lines.extend(["};", "", "#endif", ""])
    encoded = "\n".join(lines).encode("ascii")
    if not output.exists() or output.read_bytes() != encoded:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(encoded)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    if args.input.resolve() == args.output.resolve():
        parser.error("Input and output must be different files")
    try:
        convert(args.input, args.output)
    except (OSError, UnidentifiedImageError, ValueError) as error:
        parser.error(str(error))


if __name__ == "__main__":
    main()
